title: <p align="center"> Jaiganesh Jayaraman </p>
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="pdf/resume.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/jaiganesh-jayaraman/">LinkedIn</a> |
  <a href="https://github.com/JaiDevOpsGIT">GitHub</a>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
